// Copyright (c) Tailscale Inc & AUTHORS
// SPDX-License-Identifier: BSD-3-Clause

// Code generated by tailscale.com/cmd/cloner; DO NOT EDIT.

package rssbot

// Clone makes a deep copy of Subscription.
// The result aliases no memory with the original.
func (src *Subscription) Clone() *Subscription {
	if src == nil {
		return nil
	}
	dst := new(Subscription)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _SubscriptionCloneNeedsRegeneration = Subscription(struct {
	UserID       int64
	ChatID       int64
	FeedURL      string
	FeedInfo     FeedInfo
	LastChecked  string
	LastItemGUID string
}{})

// Clone makes a deep copy of FeedInfo.
// The result aliases no memory with the original.
func (src *FeedInfo) Clone() *FeedInfo {
	if src == nil {
		return nil
	}
	dst := new(FeedInfo)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _FeedInfoCloneNeedsRegeneration = FeedInfo(struct {
	Title       string
	Description string
	Link        string
}{})

// Clone makes a deep copy of FeedError.
// The result aliases no memory with the original.
func (src *FeedError) Clone() *FeedError {
	if src == nil {
		return nil
	}
	dst := new(FeedError)
	*dst = *src
	return dst
}

// A compilation failure here means this code must be regenerated, with the command at the top of this file.
var _FeedErrorCloneNeedsRegeneration = FeedError(struct {
	FeedURL      string
	ErrorCount   int
	LastError    string
	LastErrorAt  string
	FirstErrorAt string
}{})
